interface Language {
    id: string;
    name: string;
    flagCode: string; // IMPORTANT: ISO code for react-native-country-flag
}


export const LANGUAGES: Language[] = [
    { id: '1', name: 'English', flagCode: 'gb' },
    { id: '2', name: 'हिन्दी (Hindi)', flagCode: 'in' },
    { id: '3', name: 'தமிழ் (Tamil)', flagCode: 'in' },
    { id: '4', name: 'తెలుగు (Telugu)', flagCode: 'in' },
    { id: '5', name: 'മലയാളം (Malayalam)', flagCode: 'in' },
    { id: '6', name: 'ಕನ್ನಡ (Kannada)', flagCode: 'in' },
    { id: '7', name: 'मराठी (Marathi)', flagCode: 'in' },
    { id: '8', name: 'বাংলা (Bengali)', flagCode: 'bd' },
    { id: '9', name: 'ગુજરાતી (Gujarati)', flagCode: 'in' },
    { id: '10', name: 'ਪੰਜਾਬੀ (Punjabi)', flagCode: 'in' },
    { id: '11', name: 'ଓଡ଼ିଆ (Odia)', flagCode: 'in' },

    { id: '12', name: 'اردو (Urdu)', flagCode: 'pk' },
    { id: '13', name: 'नेपाली (Nepali)', flagCode: 'np' },
    { id: '14', name: 'සිංහල (Sinhala)', flagCode: 'lk' },
    { id: '15', name: '中文 (Mandarin Chinese)', flagCode: 'cn' },
    { id: '16', name: '日本語 (Japanese)', flagCode: 'jp' },
    { id: '17', name: '한국어 (Korean)', flagCode: 'kr' },
    { id: '18', name: 'Français (French)', flagCode: 'fr' },
    { id: '19', name: 'Español (Spanish)', flagCode: 'es' },
    { id: '20', name: 'Português (Portuguese)', flagCode: 'pt' },
    { id: '21', name: 'Deutsch (German)', flagCode: 'de' },
    { id: '22', name: 'Italiano (Italian)', flagCode: 'it' },
    { id: '23', name: 'Nederlands (Dutch)', flagCode: 'nl' },
    { id: '24', name: 'Русский (Russian)', flagCode: 'ru' },
    { id: '25', name: 'Українська (Ukrainian)', flagCode: 'ua' },
    { id: '26', name: 'Polski (Polish)', flagCode: 'pl' },
    { id: '27', name: 'Čeština (Czech)', flagCode: 'cz' },
    { id: '28', name: 'Magyar (Hungarian)', flagCode: 'hu' },
    { id: '29', name: 'Ελληνικά (Greek)', flagCode: 'gr' },

    // 🌍 WORLD LANGUAGES START HERE  
    { id: '30', name: 'Afrikaans', flagCode: 'za' },
    { id: '31', name: 'Amharic', flagCode: 'et' },
    { id: '32', name: 'Arabic', flagCode: 'sa' },
    { id: '33', name: 'Armenian', flagCode: 'am' },
    { id: '34', name: 'Azerbaijani', flagCode: 'az' },
    { id: '35', name: 'Basque', flagCode: 'es' },
    { id: '36', name: 'Belarusian', flagCode: 'by' },
    { id: '37', name: 'Bosnian', flagCode: 'ba' },
    { id: '38', name: 'Bulgarian', flagCode: 'bg' },
    { id: '39', name: 'Burmese', flagCode: 'mm' },
    { id: '40', name: 'Catalan', flagCode: 'es' },
    { id: '41', name: 'Croatian', flagCode: 'hr' },
    { id: '42', name: 'Danish', flagCode: 'dk' },
    { id: '43', name: 'Estonian', flagCode: 'ee' },
    { id: '44', name: 'Filipino (Tagalog)', flagCode: 'ph' },
    { id: '45', name: 'Finnish', flagCode: 'fi' },
    { id: '46', name: 'Georgian', flagCode: 'ge' },
    { id: '47', name: 'Haitian Creole', flagCode: 'ht' },
    { id: '48', name: 'Hausa', flagCode: 'ng' },
    { id: '49', name: 'Hebrew', flagCode: 'il' },
    { id: '50', name: 'Icelandic', flagCode: 'is' },
    { id: '51', name: 'Indonesian', flagCode: 'id' },
    { id: '52', name: 'Javanese', flagCode: 'id' },
    { id: '53', name: 'Kazakh', flagCode: 'kz' },
    { id: '54', name: 'Khmer', flagCode: 'kh' },
    { id: '55', name: 'Kurdish', flagCode: 'iq' },
    { id: '56', name: 'Kyrgyz', flagCode: 'kg' },
    { id: '57', name: 'Latvian', flagCode: 'lv' },
    { id: '58', name: 'Lithuanian', flagCode: 'lt' },
    { id: '59', name: 'Luxembourgish', flagCode: 'lu' },
    { id: '60', name: 'Macedonian', flagCode: 'mk' },
    { id: '61', name: 'Malagasy', flagCode: 'mg' },
    { id: '62', name: 'Malay', flagCode: 'my' },
    { id: '63', name: 'Maltese', flagCode: 'mt' },
    { id: '64', name: 'Mongolian', flagCode: 'mn' },
    { id: '65', name: 'Norwegian', flagCode: 'no' },
    { id: '66', name: 'Pashto', flagCode: 'af' },
    { id: '67', name: 'Persian (Farsi)', flagCode: 'ir' },
    { id: '68', name: 'Quechua', flagCode: 'pe' },
    { id: '69', name: 'Romanian', flagCode: 'ro' },
    { id: '70', name: 'Serbian', flagCode: 'rs' },
    { id: '71', name: 'Slovak', flagCode: 'sk' },
    { id: '72', name: 'Slovenian', flagCode: 'si' },
    { id: '73', name: 'Somali', flagCode: 'so' },
    { id: '74', name: 'Swahili', flagCode: 'ke' },
    { id: '75', name: 'Swedish', flagCode: 'se' },
    { id: '76', name: 'Tajik', flagCode: 'tj' },
    { id: '77', name: 'Thai', flagCode: 'th' },
    { id: '78', name: 'Turkish', flagCode: 'tr' },
    { id: '79', name: 'Turkmen', flagCode: 'tm' },
    { id: '80', name: 'Uzbek', flagCode: 'uz' },
    { id: '81', name: 'Vietnamese', flagCode: 'vn' },
    { id: '82', name: 'Yoruba', flagCode: 'ng' },
    { id: '83', name: 'Zulu', flagCode: 'za' },
    { id: '84', name: 'Tigrinya', flagCode: 'er' },
    { id: '85', name: 'Igbo', flagCode: 'ng' },
    { id: '86', name: 'Fijian', flagCode: 'fj' },
    { id: '87', name: 'Samoan', flagCode: 'ws' },
    { id: '88', name: 'Maori', flagCode: 'nz' },
    { id: '89', name: 'Corsican', flagCode: 'fr' },
    { id: '90', name: 'Galician', flagCode: 'es' },
    { id: '91', name: 'Yiddish', flagCode: 'il' },
    { id: '92', name: 'Hmong', flagCode: 'cn' },
    { id: '93', name: 'Lao', flagCode: 'la' },
    { id: '94', name: 'Chichewa', flagCode: 'mw' },
    { id: '95', name: 'Kinyarwanda', flagCode: 'rw' },
    { id: '96', name: 'Sesotho', flagCode: 'ls' },
    { id: '97', name: 'Shona', flagCode: 'zw' },
    { id: '98', name: 'Sundanese', flagCode: 'id' },
    { id: '99', name: 'Akan', flagCode: 'gh' },
    { id: '100', name: 'Bambara', flagCode: 'ml' },

    // ⭐ Remaining 100 languages (101–200)  
    { id: '101', name: 'Twi', flagCode: 'gh' },
    { id: '102', name: 'Wolof', flagCode: 'sn' },
    { id: '103', name: 'Mandinka', flagCode: 'gm' },
    { id: '104', name: 'Ga', flagCode: 'gh' },
    { id: '105', name: 'Ewe', flagCode: 'tg' },
    { id: '106', name: 'Dagbani', flagCode: 'gh' },
    { id: '107', name: 'Berber', flagCode: 'ma' },
    { id: '108', name: 'Tswana', flagCode: 'bw' },
    { id: '109', name: 'Tsonga', flagCode: 'za' },
    { id: '110', name: 'Venda', flagCode: 'za' },
    { id: '111', name: 'Oromo', flagCode: 'et' },
    { id: '112', name: 'Kabyle', flagCode: 'dz' },
    { id: '113', name: 'Assamese', flagCode: 'in' },
    { id: '114', name: 'Manipuri (Meitei)', flagCode: 'in' },
    { id: '115', name: 'Bodo', flagCode: 'in' },
    { id: '116', name: 'Santali', flagCode: 'in' },
    { id: '117', name: 'Konkani', flagCode: 'in' },
    { id: '118', name: 'Dogri', flagCode: 'in' },
    { id: '119', name: 'Maithili', flagCode: 'in' },
    { id: '120', name: 'Sindhi', flagCode: 'pk' },
    { id: '121', name: 'Tatar', flagCode: 'ru' },
    { id: '122', name: 'Uyghur', flagCode: 'cn' },
    { id: '123', name: 'Chuvash', flagCode: 'ru' },
    { id: '124', name: 'Sakha (Yakut)', flagCode: 'ru' },
    { id: '125', name: 'Breton', flagCode: 'fr' },
    { id: '126', name: 'Occitan', flagCode: 'fr' },
    { id: '127', name: 'Frisian', flagCode: 'nl' },
    { id: '128', name: 'Scottish Gaelic', flagCode: 'gb' },
    { id: '129', name: 'Irish Gaelic', flagCode: 'ie' },
    { id: '130', name: 'Welsh', flagCode: 'gb' },
    { id: '131', name: 'Cornish', flagCode: 'gb' },
    { id: '132', name: 'Manx', flagCode: 'gb' },
    { id: '133', name: 'Romansh', flagCode: 'ch' },
    { id: '134', name: 'Esperanto', flagCode: 'pl' },
    { id: '135', name: 'Interlingua', flagCode: 'us' },
    { id: '136', name: 'Tok Pisin', flagCode: 'pg' },
    { id: '137', name: 'Marshallese', flagCode: 'mh' },
    { id: '138', name: 'Palauan', flagCode: 'pw' },
    { id: '139', name: 'Chamorro', flagCode: 'mp' },
    { id: '140', name: 'Nauruan', flagCode: 'nr' },
    { id: '141', name: 'Tongan', flagCode: 'to' },
    { id: '142', name: 'Kiribati', flagCode: 'ki' },
    { id: '143', name: 'Bislama', flagCode: 'vu' },
    { id: '144', name: 'Maldivian (Dhivehi)', flagCode: 'mv' },
    { id: '145', name: 'Tibetan', flagCode: 'cn' },
    { id: '146', name: 'Aymara', flagCode: 'bo' },
    { id: '147', name: 'Guarani', flagCode: 'py' },
    { id: '148', name: 'Hawaiian', flagCode: 'us' },
    { id: '149', name: 'Mapudungun', flagCode: 'cl' },
    { id: '150', name: 'Mayan', flagCode: 'mx' },
    { id: '151', name: 'Nahuatl', flagCode: 'mx' },
    { id: '152', name: 'Inuktitut', flagCode: 'ca' },
    { id: '153', name: 'Cree', flagCode: 'ca' },
    { id: '154', name: 'Ojibwe', flagCode: 'ca' },
    { id: '155', name: 'Cherokee', flagCode: 'us' },
    { id: '156', name: 'Navajo', flagCode: 'us' },
    { id: '157', name: 'Lakota', flagCode: 'us' },
    { id: '158', name: 'Fula (Fulani)', flagCode: 'ne' },
    { id: '159', name: 'Bemba', flagCode: 'zm' },
    { id: '160', name: 'Luganda', flagCode: 'ug' },
    { id: '161', name: 'Kikuyu', flagCode: 'ke' },
    { id: '162', name: 'Kamba', flagCode: 'ke' },
    { id: '163', name: 'Sango', flagCode: 'cf' },
    { id: '164', name: 'Lingala', flagCode: 'cd' },
    { id: '165', name: 'Twi (Akan)', flagCode: 'gh' },
    { id: '166', name: 'Fon', flagCode: 'bj' },
    { id: '167', name: 'Zulu (Northern)', flagCode: 'za' },
    { id: '168', name: 'Xhosa', flagCode: 'za' },
    { id: '169', name: 'Setswana', flagCode: 'bw' },
    { id: '170', name: 'Sesotho sa Leboa', flagCode: 'za' },
    { id: '171', name: 'Khoekhoe', flagCode: 'na' },
    { id: '172', name: 'Tsonga', flagCode: 'za' },
    { id: '173', name: 'Kanuri', flagCode: 'ng' },
    { id: '174', name: 'Tumbuka', flagCode: 'mw' },
    { id: '175', name: 'Dagur', flagCode: 'cn' },
    { id: '176', name: 'Nanai', flagCode: 'ru' },
    { id: '177', name: 'Ainu', flagCode: 'jp' },
    { id: '178', name: 'Buryat', flagCode: 'ru' },
    { id: '179', name: 'Nenets', flagCode: 'ru' },
    { id: '180', name: 'Sami (Northern)', flagCode: 'no' },
    { id: '181', name: 'Sami (Southern)', flagCode: 'se' },
    { id: '182', name: 'Lombard', flagCode: 'it' },
    { id: '183', name: 'Sicilian', flagCode: 'it' },
    { id: '184', name: 'Aragonese', flagCode: 'es' },
    { id: '185', name: 'Asturian', flagCode: 'es' },
    { id: '186', name: 'Faroese', flagCode: 'fo' },
    { id: '187', name: 'Greenlandic (Kalaallisut)', flagCode: 'gl' },
    { id: '188', name: 'Sranan Tongo', flagCode: 'sr' },
    { id: '189', name: 'Papiamento', flagCode: 'aw' },
    { id: '190', name: 'Bhojpuri', flagCode: 'in' },
    { id: '191', name: 'Rohingya', flagCode: 'mm' },
    { id: '192', name: 'Saraiki', flagCode: 'pk' },
    { id: '193', name: 'Marwari', flagCode: 'in' },
    { id: '194', name: 'Chhattisgarhi', flagCode: 'in' },
    { id: '195', name: 'Magahi', flagCode: 'in' },
    { id: '196', name: 'Awadhi', flagCode: 'in' },
    { id: '197', name: 'Haryanvi', flagCode: 'in' },
    { id: '198', name: 'Rajasthani', flagCode: 'in' },
    { id: '199', name: 'Tulu', flagCode: 'in' },
    { id: '200', name: 'Kodava', flagCode: 'in' },
];
